# =============================================================================
# combined_map.py
# =============================================================================
# PURPOSE:
#   Read the L2 SST and Chlor-a NetCDF files produced by sst_retrieval.py
#   and chlora_retrieval.py and produce a side-by-side publication-quality
#   figure for ecological interpretation.
#
# PEDAGOGICAL NOTE — code reuse through helper functions:
#   find_l2_netcdf() and load_l2() are used here AND in sst_chla_scatter.py.
#   This demonstrates good scientific programming practice: instead of
#   copy-pasting the same file-loading code into every script, we define
#   it once and call it. In a larger project these would move to a shared
#   utils.py module.
#
# COLOUR SCALE DESIGN:
#   SST — cmocean.thermal (sequential, perceptually uniform):
#     Maps low (cold) → dark purple → orange → white (warm).
#     The 2nd–98th percentile stretch clips outlier pixels and uses the
#     full colour range for the "interesting" temperature variation.
#
#   Chlor-a — cmocean.algae + LogNorm (logarithmic normalisation):
#     Chlor-a spans 3 orders of magnitude (0.01–10 mg/m³) in a single scene.
#     A linear scale would make open-ocean variability invisible (all one colour)
#     while coastal blooms would be the only thing visible.
#     LogNorm maps log10(Chl-a) linearly onto the colour scale, making both
#     oligotrophic and eutrophic waters clearly distinguishable.
#
# PREREQUISITE:
#   Run sst_retrieval.py and chlora_retrieval.py first.
# =============================================================================
# combined_map.py
# Produces a side-by-side SST and Chlor-a map from the L2 NetCDF files
# generated by sst_retrieval.py and chlora_retrieval.py

import glob
import os
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import cmocean
from matplotlib.colors import LogNorm


def find_l2_netcdf(pattern, description):
    """
    Auto-detect a L2 NetCDF output file by glob pattern.

    Uses glob() with a wildcard (*) so the function works regardless of
    any suffix in the filename (e.g. sentinel3_SST_L2.nc or any variant).
    If multiple files match (e.g. from multiple runs), sorts by modification
    time and uses the most recent — reproducible behaviour without hard-coding.
    Raises a clear FileNotFoundError with actionable instructions if missing.
    """
    matches = glob.glob(pattern)
    if len(matches) == 0:
        raise FileNotFoundError(
            f"No {description} file found matching '{pattern}' in {os.getcwd()}\n"
            f"Run sst_retrieval.py and chlora_retrieval.py first."
        )
    if len(matches) > 1:
        print(f"Multiple {description} files found, using most recent:")
        matches.sort(key=os.path.getmtime, reverse=True)
        for m in matches: print(f"  {m}")
    print(f"Using {description}: {matches[0]}")
    return matches[0]


def load_l2(filepath, varname):
    """Open a L2 NetCDF and return (data array, lat, lon)."""
    ds = xr.open_dataset(filepath)
    data = ds[varname].values.astype(float)
    lat  = ds['lat'].values
    lon  = ds['lon'].values
    ds.close()
    return data, lat, lon


# ---- Auto-detect L2 files ----
sst_file = find_l2_netcdf('sentinel3_SST_L2*.nc',   'SST L2')
chl_file = find_l2_netcdf('sentinel3_ChlorA_L2*.nc', 'Chlor-a L2')

SST, lat_sst, lon_sst = load_l2(sst_file, 'sst')
CHL, lat_chl, lon_chl = load_l2(chl_file, 'chla')

# ---- Plot ----
fig, axes = plt.subplots(1, 2, figsize=(18, 8),
                         subplot_kw={'projection': ccrs.PlateCarree()})

for ax in axes:
    ax.add_feature(cfeature.LAND, color='#d4c5a9', zorder=3)
    ax.add_feature(cfeature.COASTLINE, linewidth=0.7, zorder=4)
    ax.gridlines(draw_labels=True, linewidth=0.4, color='gray', alpha=0.5)

# SST panel
valid_sst = np.isfinite(SST)
img1 = axes[0].pcolormesh(
    lon_sst, lat_sst, SST,
    cmap=cmocean.cm.thermal,
    vmin=np.nanpercentile(SST[valid_sst], 2),
    vmax=np.nanpercentile(SST[valid_sst], 98),
    transform=ccrs.PlateCarree(), rasterized=True
)
plt.colorbar(img1, ax=axes[0], label='SST (°C)', pad=0.02, shrink=0.85)
axes[0].set_title('Sea Surface Temperature (SST)\nSentinel-3 SLSTR L2', fontsize=11)

# Chlor-a panel
img2 = axes[1].pcolormesh(
    lon_chl, lat_chl, CHL,
    norm=LogNorm(vmin=0.01, vmax=10),
    cmap=cmocean.cm.algae,
    transform=ccrs.PlateCarree(), rasterized=True
)
cbar2 = plt.colorbar(img2, ax=axes[1], label='Chlorophyll-a (mg/m³)', pad=0.02, shrink=0.85)
cbar2.set_ticks([0.01, 0.1, 1, 10])
cbar2.set_ticklabels(['0.01', '0.1', '1', '10'])
axes[1].set_title('Chlorophyll-a Concentration\nSentinel-3 OLCI L2 (OC4ME)', fontsize=11)

fig.suptitle('Sentinel-3 L2 Products — Copernicus / ESA', fontsize=13, y=1.01)
plt.tight_layout()
plt.savefig('Sentinel3_SST_ChlorA_composite.png', dpi=150, bbox_inches='tight')
plt.close()
print("Saved: Sentinel3_SST_ChlorA_composite.png")
